source 'https://github.com/CocoaPods/Specs.git'
platform:ios, '13.0'
post_install do |installer|
  flutter_post_install(installer) if defined?(flutter_post_install)
  installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
          config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
          config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
      end
  end
end

target 'ZFPlayer_Example' do
    pod 'FDFullscreenPopGesture'
    pod 'MJRefresh'
    pod 'ZFPlayer', :path => '../'
    pod 'ZFPlayer/ControlView', :path => '../'
    pod 'ZFPlayer/AVPlayer', :path => '../'
    pod 'ZFPlayer/ijkplayer', :path => '../'
    pod 'ZFPlayer/aliplayer', :path => '../'

end
